os: Visual Studio 2015

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly-2020-01-23 --default-host x86_64-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -V
  - cargo -V
  - cargo install --git https://github.com/PyO3/maturin.git --tag v0.7.9 maturin

build_script:
- sed -i '/^name =/ s/finalfusion-python/finalfusion/' Cargo.toml
- maturin build --release

artifacts:
  - path: '**/*.whl'
    name: Wheels
