language: rust
dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5-dev
      - python3.6-dev
      - python3.6-venv
      - python3.7-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly-2019-02-07
    - os: osx
      rust: nightly-2019-02-07

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      python3 -m venv venv
      source venv/bin/activate
      pip install cffi virtualenv pytest
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python3.6 -m venv venv
      source venv/bin/activate
      pip install cffi virtualenv pytest
    fi
  - cargo install pyo3-pack --vers 0.6.1
  - rustup default nightly-2019-02-07
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - pyo3-pack develop
  - pytest
  - pyo3-pack build --release
deploy:
  provider: releases
  api_key:
    secure: KtDkbm9l+Jc91RDLE4HF6m8Eni2AGKVhLGSokroASkKvbaMUeBz9kxoSQAbJB6z2MJtq1TytlC+6VQgLPabibh5yzhaqN/Optc3k3lhBAiaPGsbSyZqpuntRu0JnulZe3Dz0Iisdprw606+58N3Nu9SdsZPaAJtyFYw23yKsEaq4bEbRYSwdELGgXBITVNHwxFDhURiR0kw3WSq/XO0yNn2bLoGYdJVzUarmnb1Q0XJEl+vr3wJ7B1BM9Z/o4d4AuoYyuS67k7LJGbdzg2RTJL1BH7TlQfYklUFuH2/Bn68gCf03P6moDeTK9JzAz4kXv64F6KMzuB+iR69tNRQ7gZqBYOJ5G/n8QrfJ0YjzECV0d6UMJt7cJB3ssZMLRtMnXNcJedS0M0IuZa2yO37foe2D2sI3sqchFHxNSFMTT5LHla4KpCe0UIdGCkfDClqgHp0Ra499rmjdTT7bzl0dsIdWPvE1QFcegKvaviugoweD7D0O8BjTkxMw2Dd+gVqhFtKJ3eBNWTS3eFaA8DbDwJqYm6cOINDakb5+M26+OkUePizPowqnfqBHNnewSl8VuZ2LJVqMT9pEoUT027kTUQyq3j13AJ7TK8R6MTEVyq+uru5G9t/BHFIVYeQ43rqEUOxbhGvlSoT0qqDtFwLRxDnLQy/raRKgpGYxDVc6osI=
  file_glob: true
  file: target/wheels/*.whl
  skip_cleanup: true
  on:
    repo: finalfusion/finalfusion-python
    tags: true
