language: rust
dist: xenial

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5-dev
      - python3.6-dev
      - python3.7-dev
      - python3.7-venv

matrix:
  fast_finish: true
  include:
    - os: linux
      rust: nightly-2019-07-19
    - if: tag IS present
      os: osx
      osx_image: xcode9.4
      rust: nightly-2019-07-19
    - os: osx
      osx_image: xcode10.1
      rust: nightly-2019-07-19

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      python3 -m venv venv
      source venv/bin/activate
      pip install cffi virtualenv pytest numpy
    fi
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      python3.7 -m venv venv
      source venv/bin/activate
      pip install cffi virtualenv pytest numpy
    fi
  - rustup default nightly-2019-07-19
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      cargo build
      cp target/debug/libfinalfusion.dylib target/debug/finalfusion.so
    else
      # The order is important, since the venv is created for Python 3.7.
      for pyVersion in 3.5 3.6 3.7; do
        echo "🐍 Testing compilation with Python ${pyVersion}"
        PYTHON_SYS_EXECUTABLE=python${pyVersion} cargo build
      done
      cp target/debug/libfinalfusion.so target/debug/finalfusion.so
    fi
  - export PYTHONPATH="$PWD/target/debug:$PYTHONPATH"
  - pytest
